apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: exijurcq6-nodejs
  janus-idp.io/tekton: exijurcq6-nodejs
  backstage.io/kubernetes-id: exijurcq6-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: exijurcq6-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
